# サイトの基本情報
title: "nuno's TIL"
description: "個人の技術ノート・学習ログ"
author: "nuno"
#email: "yourname@example.com"
url: "https://tnunokawa.github.io/til/"   # サイトのURL
#baseurl: ""                     # サブパスがある場合のみ設定（例：/blog）

# テーマ設定
#theme: minima  # GitHub Pagesで使える標準テーマ
#remote_theme: jekyll/minima@latest
theme: jekyll-theme-primer

# ナビゲーションメニューをつけたい場合（テーマによって対応）
# header_pages:
#   - index.md
#   - about.md

# Markdown設定
markdown: kramdown
highlighter: rouge

# 日付フォーマット
timezone: Asia/Tokyo

# プラグイン（GitHub Pages対応のもののみ）
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at

# Google Analyticsなどを入れたい場合
# google_analytics: G-XXXXXXXXXX
